workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod repo update
          pod install --verbose
      - name: Build iOS IPA
        script: flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - janepounds1@gmail.com
