// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL7OLNudDpKCS8r8bIg7n8efrQ4qtBB1U',
    appId: '1:931733620931:web:f61ad5ad94746ad9c5ba76',
    messagingSenderId: '931733620931',
    projectId: 'otela-project',
    authDomain: 'otela-project.firebaseapp.com',
    storageBucket: 'otela-project.firebasestorage.app',
    measurementId: 'G-DYG4PBWV92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgLOUxWcCKPfhX7n8hK3kT9mPka3f1M9k',
    appId: '1:931733620931:android:1f63a9a206165476c5ba76',
    messagingSenderId: '931733620931',
    projectId: 'otela-project',
    storageBucket: 'otela-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8VfZVGINros82Uz1gmHTustuU28oMqUo',
    appId: '1:931733620931:ios:873c2d5b84626832c5ba76',
    messagingSenderId: '931733620931',
    projectId: 'otela-project',
    storageBucket: 'otela-project.firebasestorage.app',
    iosBundleId: 'com.example.otelaInvestmentClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8VfZVGINros82Uz1gmHTustuU28oMqUo',
    appId: '1:931733620931:ios:873c2d5b84626832c5ba76',
    messagingSenderId: '931733620931',
    projectId: 'otela-project',
    storageBucket: 'otela-project.firebasestorage.app',
    iosBundleId: 'com.example.otelaInvestmentClubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL7OLNudDpKCS8r8bIg7n8efrQ4qtBB1U',
    appId: '1:931733620931:web:8cbce10472a31f84c5ba76',
    messagingSenderId: '931733620931',
    projectId: 'otela-project',
    authDomain: 'otela-project.firebaseapp.com',
    storageBucket: 'otela-project.firebasestorage.app',
    measurementId: 'G-M4XEX4BWY3',
  );
}
