platform :ios, '14.0'

# Explicitly set Flutter root
flutter_root = ENV['FLUTTER_ROOT'] || '/home/janepounds/flutter/flutter'

# Load the Flutter-specific configurations for iOS
eval(File.read(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')), binding)

target 'Runner' do
  use_frameworks! :linkage => :static
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'RunnerTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end

