name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use a macOS runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Install dependencies (CocoaPods)
        run: |
          cd ios
          flutter pub get
          pod install

      # - name: Set up Xcode
      #   run: |
      #     sudo xcode-select -s /Applications/Xcode_12.5.app/Contents/Developer
      #     sudo xcodebuild -version

      - name: Build the app
        run: |
          xcodebuild clean build -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphonesimulator

      - name: Run tests on the iOS Simulator
        run: |
          xcrun simctl boot "iPhone 12"
          xcrun simctl launch booted com.yourcompany.YourApp
          xcodebuild test -workspace ios/Runner.xcworkspace -scheme Runner -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' -quiet
