name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Clean Flutter Project
        run: flutter clean

      - name: Delete DerivedData (Xcode Cache)
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Remove & Reinstall CocoaPods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update

      - name: Disable Code Signing for
