name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use a macOS runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Install CocoaPods Dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Build the iOS App
        run: |
          cd ios
          xcodebuild clean build -workspace Runner.xcworkspace -scheme Runner -sdk iphonesimulator

      - name: Run Tests on iOS Simulator
        run: |
          xcrun simctl boot "iPhone 12"
          xcodebuild test -workspace ios/Runner.xcworkspace -scheme Runner -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' -quiet
